### ISSUE TITLE
OSCP - ZIP file and typo 

### ISSUE THREAD

**Issue by hackerinthshell** [noraj/OSCP-Exam-Report-Template-Markdown#10]
Hi noraj,

The  OSCP exam guide was updated and it is no longer needed to compress the file with a password:
https://help.offensive-security.com/hc/en-us/articles/360040165632-OSCP-Exam-Guide

![image](https://user-images.githubusercontent.com/16602436/102120592-8750e280-3e21-11eb-9be5-54515f5e7f3b.png)

There is a typo in the template OSCP-exam-report-template_whoisflynn_v3.2.md:

After collecting trophies from the exam network was completed, **Alec** removed all user accounts and passwords as well as the Meterpreter services installed on the system. 

**Alec** is the student's name and should be replaced by **I**.

**Comment by noraj** [comment]
closed by c051771e3dbd7c032803ad9b799fe253d31b6e68 and ba52c09f2c4d3fc57971fc223d0d4fbe20ed789d
