### ISSUE TITLE
Unnecessary packages - texlive

### ISSUE THREAD

**Issue by omr00t** [noraj/OSCP-Exam-Report-Template-Markdown#16]
On a debian-based system, `texlive-full` downloads a huge set of packages, and most of which are not necessary to generate the report.

The following command should install all the "necessary" packages on a debian-based system in order to generate the report:
```
sudo apt-get install pandoc texlive-fonts-extra texlive-latex-extra texlive-latex-recommended texlive-latex-base p7zip-full
```
This cuts the download size by ~4.6x (from +3GB to ~700MB) . It also cuts the disk space usage by ~3x (from +6GB to ~2GB).

**Comment by noraj** [comment]
`texlive-latex-base` is already a dependency of [`texlive-latex-recommended`](https://packages.debian.org/buster/texlive-latex-recommended) so no need to mention it.

I'll modify it.
