### ISSUE TITLE
error

### ISSUE THREAD

**Issue by catchthefloaty** [noraj/OSCP-Exam-Report-Template-Markdown#24]
had to remove a bunch of pandoc options from command to get output. 

Error producing PDF.
! Undefined control sequence.
l.332 \frontmatter

**Comment by noraj** [comment]
I can't help you much without more information. I'll close the issue until you provide more information.

**Comment by cyberpunkrooster** [comment]
I had this issue too but just worked out what the deal is in case anyone else runs into it too.
If you're not duplicating the template .md files for your own notes, make sure you at least grab the title page section out of one of the templates (everything including the "---") and put it at the top of your report. You'll no longer get the error and the PDF will generate successfully.
