### ISSUE TITLE
New OSEP template

### ISSUE THREAD

**Issue by ceso** [noraj/OSCP-Exam-Report-Template-Markdown#25]
Ey, I just modified your OSEP template for my report in a way I felt follows more the flow of the attack during the exam and wanted to share it with you as might be is useful to others as well.

The template itself is here:

```https://github.com/ceso/ceso.github.io/blob/master/files/osep/OSEP_report_template.md```

And a built pdf example from it here:

```https://github.com/ceso/ceso.github.io/blob/master/files/osep/OSEP_report_EXAMPLE.pdf```

Regards!

**Comment by noraj** [comment]
Thx @ceso for your template. I took the liberty to fix some typo and formatting to be able to be merged in the repository.

Please take a look at my PR https://github.com/noraj/OSCP-Exam-Report-Template-Markdown/pull/26/files, this is an open source project you can PR directly next time to save some time 😉

**Comment by ceso** [comment]
Thanks @noraj !

I just noticed I could just have created a PR after creating the issue :stuck_out_tongue_closed_eyes: , thanks for adding it.
