### ISSUE TITLE
[Feature Request] Python Script

### ISSUE THREAD

**Issue by aress31** [noraj/OSCP-Exam-Report-Template-Markdown#28]
It would be good to add a `python3` version of the `generate` tool. `Python3` is much widely distributed and has a large developer base than `ruby`, therefore this would make it a more obvious choice for the automating script.

> Happy to work on this feature and open a `PR` if that's something you would agree with. ☺️

**Comment by noraj** [comment]
ruby is widely available on all linux distro and people running OS cert will have it installed since they mostly already metasploit or any other tool having ruby as a dependency, so there is no real reason to create another version of the generate script.

**Comment by aress31** [comment]
Python is more widely distributed on Windows though :).

I personally use Windows as my mainly driver and occasionally hop into WSL or a Debian VM.

I do all the report from my host machine (Windows) where Python js already present. 

That's one use case if that helps.

**Comment by noraj** [comment]
> host machine (Windows) where Python js already present.

Python is not preinstalled on Windows you installed it as some point as you wan [install ruby on it](https://rubyinstaller.org/). But you are free to develop a python generator that I would be glad to add to the [Community projects](https://github.com/noraj/OSCP-Exam-Report-Template-Markdown#community-projects) section.
