### ISSUE TITLE
Insert Image

### ISSUE THREAD

**Issue by platinumvoid** [noraj/OSCP-Exam-Report-Template-Markdown#33]
What is the correct syntax of adding an image? I am using` ![](src/img/abc.png)` but I dont know how to resize/scale it and generally put it in the correct place. Thanks in advance!!

**Comment by noraj** [comment]
Hi,

See the FAQ: https://github.com/noraj/OSCP-Exam-Report-Template-Markdown/blob/master/FAQ.md#how-to-put-images-in-my-report
