### ISSUE TITLE
Using the Eisvogel template I get Latex error missing command \textquotesingle 

### ISSUE THREAD

**Issue by gr33nm0nk2802** [noraj/OSCP-Exam-Report-Template-Markdown#4]
I am new to this pandoc

**Comment by noraj** [comment]
Have you all the required packages in your TexLive install?
https://github.com/Wandmalfarbe/pandoc-latex-template#required-latex-packages

**Comment by gr33nm0nk2802** [comment]
Yes I have installed all the required packages. Pandoc seems to compile normally but using the eisvogel template to generate a pdf from the sample markdown file in the directory produces some error. Is this possible that the eisvogel latex template file is broken? could you provide me with the version of eisvogel template you used. Thanks

**Comment by noraj** [comment]
Some days ago I used the latest git version of the eisvogel template to build the to markdown template of this repository and also external documents.
Are you using the unmodified markdown template or did you start to fill it? Which command did you run with pandoc?
Can you share all details?

**Comment by noraj** [comment]
I'll re-open when having more info.
