### ISSUE TITLE
doesnt generate pdf, cant find eisvogel.latex

### ISSUE THREAD

**Issue by welpdx** [noraj/OSCP-Exam-Report-Template-Markdown#41]
Could not find data file /usr/share/pandoc/data/templates/eisvogel.latex
![img](https://i.imgur.com/nJhS7Tm.png)

Thanks

**Comment by welpdx** [comment]
Oh, do I just get it from the person who created the pandoc template? Like [here](https://github.com/Wandmalfarbe/pandoc-latex-template/releases/latest)? Thanks

**Comment by noraj** [comment]
Yeah, the requirements section (https://github.com/noraj/OSCP-Exam-Report-Template-Markdown#requirements) points to [Eisvogel Pandoc LaTeX PDF Template](https://github.com/Wandmalfarbe/pandoc-latex-template#installation).
