### ISSUE TITLE
Images from Obsidian markdown not beign rendered.

### ISSUE THREAD

**Issue by dreadlocked** [noraj/OSCP-Exam-Report-Template-Markdown#47]
Hi, I added the --resource-path to the folder where my images are stored, but the  resultant PDF still not showing the images.

I'm using Obsidian as markdown editor, it add images with this syntax: 

`![[Screenshot 2023-05-18 021312.png]]`

The path where those images are is /home/kali/report

So I edited pandoc command line from the osert.rb script and added:

`--resource-path=.:/home/kali/report/Final-Report \`

So the whole command looks like this:

```
    `pandoc #{input} -o #{pdf} \
      --from markdown+yaml_metadata_block+raw_html \
      --template eisvogel \
      --table-of-contents \
      --toc-depth 6 \
      --number-sections \
      --top-level-division=chapter \
      --highlight-style #{style} \
      --resource-path=.:/home/kali/report \
      --resource-path=.:/usr/share/osert/src
    `
```
The report shows the images as` [[Screenshot a 2023-05-17 164829.png]]` literally.

What I'm doing wrong?

**Comment by noraj** [comment]
> I'm using Obsidian as markdown editor, it add images with this syntax:
> 
> `![[Screenshot 2023-05-18 021312.png]]`

This is not valid markdown syntax, it's a custom Obsidian markup that works only with Obsidian and nowhere else.

Use a valid image syntax instead https://spec.commonmark.org/0.30/#images

**Comment by ismaildawoodjee** [comment]
@dreadlocked  In your Obsidian options in `Files & Links`, the option `Use [[Wikilinks]]` should be disabled:

![image](https://github.com/noraj/OSCP-Exam-Report-Template-Markdown/assets/58870992/2da00683-25ef-43ee-800e-c8f6779f0e52)
